service: ffmpeg-layer
frameworkVersion: ">=1.34.0 <2.0.0"
provider:
  name: aws
  region: ${file(./${opt:stage}.yml):region}
layers:
  ffmpeg:
    path: layer

resources:
  Outputs:
    FfmpegLayerExport:
      Value:
        Ref: FfmpegLambdaLayer
      Export:
        Name: FfmpegLambdaLayer